### ISSUE TITLE
is it possible to extract features from images?

### ISSUE THREAD

**Issue by anguoyang** [xhuvom/darknetFaceID#6]

**Comment by xhuvom** [comment]
What kinda features? The code here could extract face images cropped and save to image file.

**Comment by anguoyang** [comment]
@xhuvom  I need to extract face images into vectors, say, 2048 bytes, so each face has unique vector, when we compare face A and B, we could calculate the similarity between vectorA and vectorB, then we could get a ratio, e.g. 0.85 which means A and B are similar to each other with 85%, which probably the same person. if it is 0.15, then A and B are different.
we could not just use images for comparison for 1:N senario, so we need to convert images into vectors or byte arrays.

**Comment by xhuvom** [comment]
I see, you are talking about face landmarks. There is plenty of methods to do that. This fork is all about end-to-end facial recognition, not from landmarks. Thanks.
